name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd front-end   # Navega até o diretório do front-end
          npm install  # Instala as dependências do front-end

      - name: Run Cypress tests
        run: npx cypress run --config-file front-end/cypress.config.ts
        


